/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmModal: typeof import('./components/modal/InputModal.vue')['default']
    copy: typeof import('./components/chart/YearScatter copy.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputModal: typeof import('./components/modal/InputModal.vue')['default']
    LineChart: typeof import('./components/chart/LineChart.vue')['default']
    MoonPhaseCalendar: typeof import('./components/MoonPhaseCalendar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VariableCard: typeof import('./components/VariableCard.vue')['default']
    YearBoxplot: typeof import('./components/chart/YearBoxplot.vue')['default']
    YearHeatmap: typeof import('./components/chart/YearHeatmap.vue')['default']
    YearlyMonthRankingTable: typeof import('./components/table/YearlyMonthRankingTable.vue')['default']
    YearScatter: typeof import('./components/chart/YearScatter.vue')['default']
  }
}
